name: Appium CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and Run Appium Server
      run: |
        chmod +x ./scripts/start-sdk.sh
        chmod +x ./scripts/install-android-sdk.sh
        chmod +x ./scripts/emulator-up.sh
        chmod +x ./scripts/RunAppiumServer.sh # install and run appium server in the background
        ./scripts/RunAppiumServer.sh

    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
    - run: java -version

    - name: get java version
      run: |
        java -version

    - name: Install android SDK
      run: |
        ./scripts/install-android-sdk.sh

    - name: run sdk
      run: |
        ./scripts/start-sdk.sh
    - name: Install emulator
      run: |
        ./scripts/emulator-up.sh